name: nf-ggi

channels:
    - conda-forge
    - bioconda

dependencies:
    - python==3.12
    - pip
    - bioconda::hhsuite
    - conda-forge::jq
    - conda-forge::rdkit
    - pip:
        - "yunta[cuda12]"